#!/usr/bin/env python3
"""Generate shared profile and event constants for Python, TypeScript, and Go."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def quoted(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def main() -> int:
    trace_schema = json.loads((ROOT / "ualf-trajectory.schema.json").read_text(encoding="utf-8"))
    events = trace_schema["$defs"]["event"]["properties"]["type"]["enum"]
    profiles = ["ualf-trace/v1", "ualf-dataset/v1.1", "ualf-capture/v1", "ualf-amendments/v1", "ualf-retention/v1", "ualf-projection-manifest/v1", "ualf-index/v1", "ualf-analytics/v1", "ualf-segments/v1"]
    python_text = "# Generated by generate_sdk_types.py; do not edit.\nfrom typing import Final, Literal\n\nPROFILES: Final = (" + quoted(profiles) + ")\nEVENT_TYPES: Final = (" + quoted(events) + ")\nProfile = Literal[" + quoted(profiles) + "]\nEventType = Literal[" + quoted(events) + "]\n"
    ts_text = "// Generated by generate_sdk_types.py; do not edit.\nexport const PROFILES = [" + quoted(profiles) + "] as const;\nexport const EVENT_TYPES = [" + quoted(events) + "] as const;\nexport type Profile = typeof PROFILES[number];\nexport type EventType = typeof EVENT_TYPES[number];\n"
    go_profiles = "\n".join(f'\tProfile{i} Profile = {json.dumps(value)}' for i, value in enumerate(profiles))
    go_events = "\n".join(f'\tEventType{i} EventType = {json.dumps(value)}' for i, value in enumerate(events))
    go_text = f"// Code generated by generate_sdk_types.py; DO NOT EDIT.\npackage ualf\n\ntype Profile string\ntype EventType string\n\nconst (\n{go_profiles}\n)\n\nconst (\n{go_events}\n)\n"
    outputs = {ROOT / "sdk" / "python" / "ualf_types.py": python_text, ROOT / "sdk" / "typescript" / "ualf-types.ts": ts_text, ROOT / "sdk" / "go" / "types.go": go_text}
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
    print("Generated Python, TypeScript, and Go constants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
