// Code generated by generate_sdk_types.py; DO NOT EDIT.
package ualf

type Profile string
type EventType string

const (
	Profile0 Profile = "ualf-trace/v1"
	Profile1 Profile = "ualf-dataset/v1.1"
	Profile2 Profile = "ualf-capture/v1"
	Profile3 Profile = "ualf-amendments/v1"
	Profile4 Profile = "ualf-retention/v1"
	Profile5 Profile = "ualf-projection-manifest/v1"
	Profile6 Profile = "ualf-index/v1"
	Profile7 Profile = "ualf-analytics/v1"
	Profile8 Profile = "ualf-segments/v1"
)

const (
	EventType0 EventType = "model_call.started"
	EventType1 EventType = "model_call.completed"
	EventType2 EventType = "tool_call.started"
	EventType3 EventType = "tool_call.completed"
	EventType4 EventType = "observation.received"
	EventType5 EventType = "decision.recorded"
	EventType6 EventType = "file_change.recorded"
	EventType7 EventType = "state_change.recorded"
	EventType8 EventType = "error.recorded"
	EventType9 EventType = "retry.started"
	EventType10 EventType = "human_feedback.recorded"
	EventType11 EventType = "evaluation.completed"
)
