// Code generated by generate_sdk_types.py; DO NOT EDIT.
package ualf

type Profile string
type EventType string

const (
	Profile0 Profile = "ualf-trace/v1.1"
	Profile1 Profile = "ualf-dataset/v1.2"
	Profile2 Profile = "ualf-capture/v1.1"
	Profile3 Profile = "ualf-amendments/v1"
	Profile4 Profile = "ualf-retention/v1.1"
	Profile5 Profile = "ualf-rights-attestation/v1"
	Profile6 Profile = "ualf-hygiene/v1"
	Profile7 Profile = "ualf-replay-verification/v1"
	Profile8 Profile = "ualf-datasheet/v1"
	Profile9 Profile = "ualf-erasure-statement/v1"
	Profile10 Profile = "ualf-projection-manifest/v1"
	Profile11 Profile = "ualf-index/v1"
	Profile12 Profile = "ualf-analytics/v1"
	Profile13 Profile = "ualf-segments/v1"
)

const (
	EventType0 EventType = "agent.started"
	EventType1 EventType = "agent.completed"
	EventType2 EventType = "delegation.started"
	EventType3 EventType = "delegation.completed"
	EventType4 EventType = "agent_message.sent"
	EventType5 EventType = "agent_message.received"
	EventType6 EventType = "guardrail.evaluated"
	EventType7 EventType = "retrieval.completed"
	EventType8 EventType = "memory.accessed"
	EventType9 EventType = "model_call.started"
	EventType10 EventType = "model_call.completed"
	EventType11 EventType = "tool_call.started"
	EventType12 EventType = "tool_call.completed"
	EventType13 EventType = "observation.received"
	EventType14 EventType = "decision.recorded"
	EventType15 EventType = "file_change.recorded"
	EventType16 EventType = "state_change.recorded"
	EventType17 EventType = "error.recorded"
	EventType18 EventType = "retry.started"
	EventType19 EventType = "human_feedback.recorded"
	EventType20 EventType = "evaluation.completed"
)
