# Generated by generate_sdk_types.py; do not edit.
from typing import Final, Literal

PROFILES: Final = ("ualf-trace/v1", "ualf-dataset/v1.1", "ualf-capture/v1", "ualf-amendments/v1", "ualf-retention/v1", "ualf-projection-manifest/v1", "ualf-index/v1", "ualf-analytics/v1", "ualf-segments/v1")
EVENT_TYPES: Final = ("model_call.started", "model_call.completed", "tool_call.started", "tool_call.completed", "observation.received", "decision.recorded", "file_change.recorded", "state_change.recorded", "error.recorded", "retry.started", "human_feedback.recorded", "evaluation.completed")
Profile = Literal["ualf-trace/v1", "ualf-dataset/v1.1", "ualf-capture/v1", "ualf-amendments/v1", "ualf-retention/v1", "ualf-projection-manifest/v1", "ualf-index/v1", "ualf-analytics/v1", "ualf-segments/v1"]
EventType = Literal["model_call.started", "model_call.completed", "tool_call.started", "tool_call.completed", "observation.received", "decision.recorded", "file_change.recorded", "state_change.recorded", "error.recorded", "retry.started", "human_feedback.recorded", "evaluation.completed"]
