// Generated by generate_sdk_types.py; do not edit.
export const PROFILES = ["ualf-trace/v1", "ualf-dataset/v1.1", "ualf-capture/v1", "ualf-amendments/v1", "ualf-retention/v1", "ualf-projection-manifest/v1", "ualf-index/v1", "ualf-analytics/v1", "ualf-segments/v1"] as const;
export const EVENT_TYPES = ["model_call.started", "model_call.completed", "tool_call.started", "tool_call.completed", "observation.received", "decision.recorded", "file_change.recorded", "state_change.recorded", "error.recorded", "retry.started", "human_feedback.recorded", "evaluation.completed"] as const;
export type Profile = typeof PROFILES[number];
export type EventType = typeof EVENT_TYPES[number];
